- name: Create vscode directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
  loop:
    - { path: ~/Library/Application Support/Code/User }
    - { path: ~/.vscode/extensions }

- name: Setup vscode config
  ansible.builtin.file:
    src: "{{ ROLES_FOLDER }}/vscode/files/settings.json"
    path: ~/Library/Application Support/Code/User/settings.json
    state: link

- name: Get adhoc vscode extensions
  register: adhoc_vscode_extensions
  ansible.builtin.find:
    paths: ~/.vscode/extensions/
    excludes: "{{ vscode_extensions }}"
    file_type: directory
    use_regex: yes
    patterns: .*

- name: Delete adhoc vscode extensions
  loop: "{{ adhoc_vscode_extensions.files }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent

- name: Install vscode extensions
  register: result
  changed_when: '"successfully installed" in result.stdout'
  ansible.builtin.command:
    cmd: |
      code
      {% for item in vscode_extensions %}
      --install-extension {{ item }}
      {% endfor %}
