- name: Setup dock preferences
  changed_when: false
  ansible.builtin.shell:
    cmd: |
      {% for item in preferences %}
      defaults write com.apple.dock {{ item.key }} -{{ item.type }} {{ item.value }} {% if not loop.last %} && {% endif %}
      {% endfor %}
  vars:
    preferences:
      # Don’t show recent applications
      - { key: show-recents, type: bool, value: false }

      # Remove application icons
      - { key: persistent-apps, type: null, value: null }
      - { key: recent-apps, type: null, value: null }

      # Set the icon size of Dock items
      - { key: tilesize, type: int, value: 36 }
      - { key: size-immutable, type: bool, value: true }

      # Show only open applications in the Dock
      - { key: static-only, type: bool, value: true }

      # Don’t animate opening applications from the Dock
      - { key: launchanim, type: bool, value: false }

      # Enable autohide
      - { key: autohide, type: bool, value: true }

      # Remove autohide delay
      - { key: autohide-delay, type: float, value: 0 }

      # Don’t show Dashboard as a Space
      - { key: dashboard-in-overlay, type: bool, value: true }
