- name: Get Mac serial number
  shell: system_profiler SPHardwareDataType | awk '/Serial/ {print $4}'
  register: mac_serial
  changed_when: false

- name: Setup login items
  changed_when: false
  ansible.builtin.command:
    cmd: |
      osascript
      -e 'tell application "System Events" to delete every login item'
      {% for item in login_items %}
      -e 'tell application "System Events" to make login item with properties { path: "/Applications/{{ item }}.app", hidden: true }'
      {% endfor %}

- name: Setup 1.1.1.1 DNS servers
  changed_when: false
  ansible.builtin.shell:
    cmd: |
      networksetup -setdnsservers Wi-Fi Empty &&
      networksetup -setdnsservers Wi-Fi 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001

- name: Disable sleep
  become: yes
  changed_when: false
  ansible.builtin.command:
    cmd: pmset -a displaysleep 0 disksleep 0 sleep 0

- name: Disable screen saver
  changed_when: false
  ansible.builtin.command:
    cmd: defaults -currentHost write com.apple.screensaver idleTime 0

- name: Disable emoji suggestion menu
  become: yes
  changed_when: false
  ansible.builtin.command:
    cmd: defaults write /Library/Preferences/FeatureFlags/Domain/UIKit.plist emoji_enhancements -dict-add Enabled -bool NO

- name: Prefer open in tabs
  become: yes
  changed_when: false
  ansible.builtin.command:
    cmd: defaults write AppleWindowTabbingMode -string always

- name: Import dock.yaml
  import_tasks: dock.yaml

- name: Import finder.yaml
  import_tasks: finder.yaml

- name: Import system.yaml
  import_tasks: system.yaml

- name: Import chime.yaml
  import_tasks: chime.yaml
  when: mac_serial.stdout != work_mac_serial
