- name: Create disable startup sound script
  become: true
  copy:
    content: |
      #!/bin/bash
      osascript -e 'set volume without output muted'
    dest: "/usr/local/bin/disable_startup_sound.sh"
    mode: "0755"

- name: Create disable logout sound script
  become: true
  copy:
    content: |
      #!/bin/bash
      osascript -e 'set volume with output muted'
    dest: "/usr/local/bin/disable_logout_sound.sh"
    mode: "0755"

- name: Setup system preferences
  changed_when: false
  become: true
  ansible.builtin.shell:
    cmd: |
      {% for item in preferences %}
      defaults write {{ item.domain }} {{ item.key }} -{{ item.type }} {{ item.value }} {% if not loop.last %} && {% endif %}
      {% endfor %}
  vars:
    preferences:
      # Enable natural scrolling
      - {
          domain: NSGlobalDomain,
          key: com.apple.swipescrolldirection,
          type: bool,
          value: true,
        }

      # Disable dashboard
      - {
          domain: om.apple.dashboard,
          key: mcx-disabled,
          type: bool,
          value: true,
        }

      # Disable "Swipe between pages"
      - {
          domain: NSGlobalDomain,
          key: AppleEnableSwipeNavigateWithScrolls,
          type: bool,
          value: false,
        }
      - {
          domain: com.google.Chrome,
          key: AppleEnableSwipeNavigateWithScrolls,
          type: bool,
          value: false,
        }

      # Enable tab selection for all elements in modal dialogs
      - {
          domain: NSGlobalDomain,
          key: AppleKeyboardUIMode,
          type: int,
          value: 3,
        }

      # Set "Delay Until Repeat" to shortest and "Key Repeat" to fastest
      - { domain: NSGlobalDomain, key: InitialKeyRepeat, type: int, value: 15 }
      - { domain: NSGlobalDomain, key: KeyRepeat, type: int, value: 2 }

      # Disable "Correct spelling automatically"
      - {
          domain: NSGlobalDomain,
          key: NSAutomaticSpellingCorrectionEnabled,
          type: bool,
          value: false,
        }

      # Always show filename extensions
      - {
          domain: NSGlobalDomain,
          key: AppleShowAllExtensions,
          type: bool,
          value: true,
        }

      # Disable tap to click
      - {
          domain: com.apple.AppleMultitouchTrackpad,
          key: Clicking,
          type: bool,
          value: false,
        }

      # Use "HH:mm" format in clock
      - {
          domain: com.apple.menuextra.clock,
          key: DateFormat,
          type: string,
          value: HH:mm,
        }

      # Disable screenshots preview thumbnails
      - {
          domain: com.apple.screencapture,
          key: show-thumbnail,
          type: bool,
          value: false,
        }

      # Save screenshots to ~/Downloads
      - {
          domain: com.apple.screencapture,
          key: location,
          type: string,
          value: "${HOME}/Downloads",
        }
