---
apt_repos:
  - name: diff-so-fancy
    uri: https://ppa.launchpadcontent.net/aos1/diff-so-fancy/ubuntu
    key_id: 4466B73F97EF279EC64D8A169E8A0C808486162E
  - name: copyq
    uri: https://ppa.launchpadcontent.net/hluk/copyq/ubuntu
    key_id: 407DCF2158B84056D11BBC944F0B2F06AA07D22F

apt_packages:
  - bat
  - build-essential
  - cmake
  - copyq
  - cowsay
  - curl
  - dconf-cli
  - diff-so-fancy
  - fd-find
  - ffmpeg
  - flac
  - fzf
  - gcc
  - git
  - git-lfs
  - gnupg
  - grep
  - guake
  - htop
  - httpie
  - jq
  - neovim
  - nginx
  - nmap
  - openssh-client
  - openssh-server
  - pipenv
  - python3
  - python3-debian
  - python3-pip
  - python3-psutil
  - python3-venv
  - rename
  - ripgrep
  - ruby
  - screen
  - silversearcher-ag
  - tldr
  - tmux
  - tree
  - unzip
  - vim
  - virtualenv
  - wget
  - xclip
  - yarn
  - yq
  - zsh
  - zsh-syntax-highlighting
