---
apt_repos:
  - name: diff-so-fancy
    uri: https://ppa.launchpadcontent.net/aos1/diff-so-fancy/ubuntu
    key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE437E0D40E6CBCE8B7FCA422ACA06DEB1FC4E1A4
  - name: copyq
    uri: https://ppa.launchpadcontent.net/hluk/copyq/ubuntu
    key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x98B2B859B6B27B071E87A9FB2DD11FBAB4BE9B6F

apt_packages:
  - bat
  - build-essential
  - cmake
  - copyq
  - cowsay
  - curl
  - dconf-cli
  - diff-so-fancy
  - fd-find
  - ffmpeg
  - flac
  - fzf
  - gcc
  - git
  - git-lfs
  - gnupg
  - grep
  - guake
  - htop
  - httpie
  - jq
  - neovim
  - nginx
  - nmap
  - openssh-client
  - openssh-server
  - pipenv
  - python3
  - python3-debian
  - python3-pip
  - python3-psutil
  - python3-venv
  - rename
  - ripgrep
  - ruby
  - screen
  - silversearcher-ag
  - tldr
  - tmux
  - tree
  - unzip
  - vim
  - virtualenv
  - wget
  - xclip
  - yarn
  - yq
  - zsh
  - zsh-syntax-highlighting
