---
- name: Create NVM directory
  file:
    path: "{{ nvm_dir }}"
    state: directory
    mode: '0755'

- name: Check if NVM is installed
  ansible.builtin.stat:
    path: "{{ nvm_dir }}/nvm.sh"
  register: nvm_installed

- name: Install NVM
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    creates: "{{ nvm_dir }}/nvm.sh"
  environment:
    NVM_DIR: "{{ nvm_dir }}"
  when: not nvm_installed.stat.exists

- name: Install Node.js LTS
  ansible.builtin.shell: |
    export NVM_DIR="{{ nvm_dir }}"
    source "$NVM_DIR/nvm.sh"
    nvm install --lts
  args:
    executable: /bin/bash
  register: node_lts_install
  ignore_errors: true

- name: Check Node.js LTS installation
  fail:
    msg: 'Could not install Node.js LTS'
  when: node_lts_install.rc != 0

- name: Install latest Node.js version
  ansible.builtin.shell: |
    export NVM_DIR="{{ nvm_dir }}"
    source "$NVM_DIR/nvm.sh"
    nvm install node
  args:
    executable: /bin/bash
  register: node_latest_install
  ignore_errors: true

- name: Set LTS as default
  ansible.builtin.shell: |
    export NVM_DIR="{{ nvm_dir }}"
    source "$NVM_DIR/nvm.sh"
    nvm alias default lts/*
  args:
    executable: /bin/bash
